### ISSUE TITLE
UE5 Say : Can't Build/Rebuild the Plugin.

### ISSUE THREAD

**Issue by shimakazevn** [axilesoft/IM-for-UE5#4]

**Comment by shimakazevn** [comment]
I did all the same steps as the instructions, but UE5 reported that the IM4U Plugin needs to be rebuilt and after clicking OK, it said it failed.

**Comment by axilesoft** [comment]
not sure what's wrong, have you re-genrate the  project? right click uproject file to select

**Comment by Cyberpunk2077-404** [comment]
1>D:\TY\UE\Projects\IM4U5\Plugins\IM-for-UE5\Source\IM4U\IM4U.Build.cs : warning : Referenced directory 'D:\UE_5.1\Engine\Source\ControlRig\Public' does not exist.
1>D:\TY\UE\Projects\IM4U5\Plugins\IM-for-UE5\Source\IM4U\IM4U.Build.cs : warning : Referenced directory 'D:\UE_5.1\Engine\Source\ControlRigDeveloper\Public' does not exist.
1>D:\TY\UE\Projects\IM4U5\Plugins\IM-for-UE5\Source\IM4U\IM4U.Build.cs : warning : Referenced directory 'D:\UE_5.1\Engine\Source\ControlRigEditor\Public' does not exist.
1>EXEC : warning : Plugin 'IM4U' does not list plugin 'ControlRig' as a dependency, but module 'IM4U' depends on 'ControlRig'.
1>EXEC : warning : Plugin 'IM4U' does not list plugin 'ControlRig' as a dependency, but module 'IM4U' depends on 'ControlRigEditor'.
1>EXEC : warning : Plugin 'IM4U' does not list plugin 'ControlRig' as a dependency, but module 'IM4U' depends on 'ControlRigDeveloper'.

**Comment by Cyberpunk2077-404** [comment]
hello, can't build in ue5.1.1, it say some referenced directory does not exist
1>D:\TY\UE\Projects\IM4U5\Plugins\IM-for-UE5\Source\IM4U\IM4U.Build.cs : warning : Referenced directory 'D:\UE_5.1\Engine\Source\ControlRig\Public' does not exist.
1>D:\TY\UE\Projects\IM4U5\Plugins\IM-for-UE5\Source\IM4U\IM4U.Build.cs : warning : Referenced directory 'D:\UE_5.1\Engine\Source\ControlRigDeveloper\Public' does not exist.
1>D:\TY\UE\Projects\IM4U5\Plugins\IM-for-UE5\Source\IM4U\IM4U.Build.cs : warning : Referenced directory 'D:\UE_5.1\Engine\Source\ControlRigEditor\Public' does not exist.
1>EXEC : warning : Plugin 'IM4U' does not list plugin 'ControlRig' as a dependency, but module 'IM4U' depends on 'ControlRig'.
1>EXEC : warning : Plugin 'IM4U' does not list plugin 'ControlRig' as a dependency, but module 'IM4U' depends on 'ControlRigEditor'.
1>EXEC : warning : Plugin 'IM4U' does not list plugin 'ControlRig' as a dependency, but module 'IM4U' depends on 'ControlRigDeveloper'.

**Comment by MrTegs** [comment]
glm problem, please help

10>PmxImporter.cpp(7): Error C1083 : Cannot open include file: 'glm/glm.hpp': No such file or directory
[9/12] Compile [x64] Module.IM4U.1.cpp
10>VmdFactory.cpp(202): Warning C4996 : 'FMessageDialog::Open': Use the overload of Open that takes the Title by-value. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>VmdFactory.cpp(224): Warning C4996 : 'FMessageDialog::Open': Use the overload of Open that takes the Title by-value. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>VmdFactory.cpp(288): Warning C4996 : 'FMessageDialog::Open': Use the overload of Open that takes the Title by-value. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>VmdFactory.cpp(538): Warning C4996 : 'IAnimationDataController::UpdateCurveNamesFromSkeleton': This function is no longer used. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>VmdFactory.cpp(652): Warning C4996 : 'IAnimationDataController::UpdateCurveNamesFromSkeleton': This function is no longer used. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>VmdFactory.cpp(725): Warning C4996 : 'USkeleton::GetSmartNameContainer': This function is no longer used Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>VmdFactory.cpp(745): Warning C4996 : 'FSmartNameMapping::Exists': FSmartNameMapping functions are no longer used. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>VmdFactory.cpp(818): Warning C4996 : 'USkeleton::AddSmartNameAndModify': Please use AddCurveMetaData. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>VmdFactory.cpp(820): Warning C4996 : 'FAnimationCurveIdentifier::FAnimationCurveIdentifier': Please use the constructor that takes an FName Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>VmdFactory.cpp(2184): Warning C4996 : 'IAnimationDataModel::GetBoneAnimationTracks': GetBoneAnimationTracks has been deprecated Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>PmxFactory.cpp(543): Warning C4996 : 'StaticFindObjectFast': Support for searching for objects in ANY_PACKAGE has been deprecated. Please provide the actual Outer of an object you want to find. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
10>PmxFactory.cpp(566): Warning C4996 : 'StaticFindObjectFast': Support for searching for objects in ANY_PACKAGE has been deprecated. Please provide the actual Outer of an object you want to find. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
Total time in Parallel executor: 36.46 seconds
Total execution time: 39.21 seconds
10>Microsoft.MakeFile.Targets(44,5): Error MSB3073 : The command ""D:\Program Files\Epic\UE_5.3\Engine\Build\BatchFiles\Build.bat" ConcertEditor Win64 Development -Project="D:\Documents\Projects\Unreal projects\Concert\Concert.uproject" -WaitMutex -FromMsBuild" exited with code 6.

**Comment by Gaalee** [comment]
Hi same problem here : 
![image](https://github.com/axilesoft/IM-for-UE5/assets/30228085/b3e58b26-56a5-4f76-b95c-2bcd9a2b9961)

![image](https://github.com/axilesoft/IM-for-UE5/assets/30228085/ef9fe445-82ad-4ec2-b68a-4f0e5e2b11be)

Tried with 5.2 an 5.3 it doesn't work.

**Comment by AkagiVoid** [comment]
> not sure what's wrong, have you re-genrate the project? right click uproject file to select

Followed all the steps and still got teh same thing as Gaalee. >w>
![{31920F6E-E189-44BB-963B-D287EDFAEC3D}](https://github.com/user-attachments/assets/01871cd0-e7f2-41df-800e-db820347aa31)

Can U zip the actual 3rd person template project with plugin and upload it to a mediafire or sumthing? >w<

Log from VS2022. >w>
[VS2022_ErrorLog.txt](https://github.com/user-attachments/files/18216477/VS2022_ErrorLog.txt)
